### ISSUE TITLE
When running harvesters start from yesterday

### ISSUE THREAD

**Issue by chrisseto** [fabianvf/scrapi#133]
When a harvester is run it will collect data from the current day.
This means that If I run harvester X at 9am then any data that appears at 10pm will be missed.

Running a harvester should have it collect data from the previous day to avoid missing any data.

**Comment by fabianvf** [comment]
:+1:

**Comment by fabianvf** [comment]
How would this interact with scrapi/requests.py?

**Comment by chrisseto** [comment]
Ideally we fix this and #134 then wipe the table in cassandra to avoid any missing data.

We would just have to be more mindful about how we create urls.
In cases such as biomed we may have to avoid storing all together.

**Comment by erinspace** [comment]
This was fixed in #189!
