### ISSUE TITLE
Need PLOS API key to run the tests

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#140]
This seems a bit intensive to make newcomers register for a PLOS account. Perhaps we can skip PLOS in tests to avoid this?

**Comment by fabianvf** [comment]
yeah... This is definitely a bug.

**Comment by fabianvf** [comment]
I haven't been able to replicate this locally, are you sure the issue was from not defining the API key?

**Comment by fabianvf** [comment]
Update? Travis build currently runs test with no API key, so this may have been a different issue.

**Comment by erinspace** [comment]
Also cannot reproduce, I think this was a sperate issue. In fact, running tests with a fresh install without a PLOS API key returns an error: 

```
ERROR:scrapi.harvesters.plos:No PLOS_API_KEY found, PLoS will always return [] 
``` 

...but tests still run successfully. Closing this one!
