### ISSUE TITLE
Add documentation to clarify where to get property lists for OAI providers

### ISSUE THREAD

**Issue by Magentashades** [fabianvf/scrapi#152]

**Comment by fabianvf** [comment]
@erinspace, would it be possible to pull out that tool you developed for the django app and make an invoke task for gathering property lists from OAI providers?

**Comment by erinspace** [comment]
YES! That'd be awesome. I've found that and a lot more documentation are needed...

**Comment by erinspace** [comment]
This has been taken care of in the [SHARE Documentation](https://osf.io/wur56/wiki/Creating%20a%20Harvester/) on creating a harvester, and also done automatically in the [auto oai tool](https://github.com/erinspace/autooai). 

Thanks so much again @Magentashades for hanging out and helping at pycon!
