### ISSUE TITLE
pubmed central urls point to identifiers in metadata, not pubmed central resources

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#165]
Pubmed central canonical URIs should not point to identifiers in the body of the record, but instead be updated to point to a PMC resource, using the PMC identifier in the record header along with the base PMC url.

**Comment by fabianvf** [comment]
@erinspace, this can be closed, right?

**Comment by erinspace** [comment]
Yep! This was resolved with the latest release.
