### ISSUE TITLE
change shortname of pubmed to pubmed central

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#166]
Graphs and searching on the example OSF Search page for SHARE metadata expose the shortname for  PubMed Central as pubmed. Update this shortname everywhere to instead read pubmedcentral.

**Comment by erinspace** [comment]
Being addressed in https://github.com/fabianvf/scrapi/pull/160

**Comment by erinspace** [comment]
temporary fix for graphs in https://github.com/CenterForOpenScience/osf.io/pull/2524, but will be addressed further with more extensive fixes mentioned above

**Comment by fabianvf** [comment]
This has been resolved in production.
