### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#171]
this would be great!

**Comment by fabianvf** [comment]
@mehanig mentioned that he was working on this

**Comment by fabianvf** [comment]
@chrisseto @jeffspies @erinspace 
If we do get python 3 support, is there any reason to continue supporting python 2? All of our libraries are compatible.

**Comment by chrisseto** [comment]
I see no reason to support both 2 and 3. It would be a huge headache to have to juggle handling unicode in both 2 and 3 at little to no gain.

**Comment by mehanig** [comment]
@fabianvf @chrisseto are you planning to switch to py3 than? py3 version is ready, waiting for some codestyle fixes

**Comment by fabianvf** [comment]
Yes, we are considering it. Seeing how much of a headache it is to get some of the stuff working in both versions in your PR makes me think it may be better to just rip the bandaid off and go for 3 support. Downside is additional devops work, which may force us to delay the merge a bit.

**Comment by mehanig** [comment]
@fabianvf good to hear that! Besides codestyle fixes, py3 version freezes while using 'inv test', while running individual tests is OK.

**Comment by fabianvf** [comment]
It may be an issue with tearing down the database connections. I'll look into it a bit more and let you know.

**Comment by JeffSpies** [comment]
So maintaining 2 and 3 compatibility has been difficult?

**Comment by fabianvf** [comment]
Yes, particularly with string data validation. If there is no compelling reason to continue support for python 2, then it adds needless overhead and complexity. If there is a good reason to keep supporting it, it's not too hard, but it will take extra time.

**Comment by erinspace** [comment]
There's a new PR up addressing this - tests pass locally in both 2.7 and 3.4 but travis is still not working smoothly - https://github.com/fabianvf/scrapi/pull/244
