### ISSUE TITLE
periodic cassandra setup cqlengine error message

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#210]
cassandra.cqlengine.CQLEngineException: It is required to setup() cqlengine before executing queries

periodic error when harvesting. Investigate and fix!

**Comment by erinspace** [comment]
@fabianvf is this still happening?

**Comment by fabianvf** [comment]
This happens when the cassandra connection dies and the workers fail to reconnect. Requires a restart of the workers/scheduler atm.

**Comment by erinspace** [comment]
Fixed for now, closing!
