### ISSUE TITLE
Add registered provider Hacettepe University, Department of Information Management

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#237]
The Department of Information Management aims to educate creative and self-confident information professionals with and leadership capabilities who can design, implement and run information systems so that individuals, organizations and the society can get the utmost benefit from the recorded, printed and electronic information repositories; and train the new generation of researchers with a high degree of knowledge about their specialties who can conduct original research and offer the new knowledge produced to the service of the society. It also strives to carry out theoretical and applied research and publish results to further the development of information systems, information services and information technologies on national and international levels.

OAI Endpoint - http://bbytezarsivi.hacettepe.edu.tr/oai/request

**Comment by erinspace** [comment]
Can use the autooai generator for this one - https://github.com/erinspace/autooai

**Comment by fabianvf** [comment]
Closed with #259
