### ISSUE TITLE
Events with multiple descriptions

### ISSUE THREAD

**Issue by samanehsan** [fabianvf/scrapi#243]
like http://repository.asu.edu/items/2834.dc.xml

need to be discussed. Searched for via:

(contributors.family:Smith and source:asu)

**Comment by samanehsan** [comment]
Ping @JeffSpies

**Comment by fabianvf** [comment]
I only see a single description in the linked document, did you mean to link something else?

**Comment by erinspace** [comment]
There should be several elements with the <dc:description> tag, look again!

**Comment by erinspace** [comment]
This might be more of a schema issue -  moved onto https://github.com/JeffSpies/SHARE-Schema/issues/13
