### ISSUE TITLE
Gather more OSF registrations

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#281]
Right now only 100 OSF registrations are showing up on SHARE - but there are over 1000 that should be picked up. 

Do a back harvest to gather all OSF registrations

**Comment by fabianvf** [comment]
I think part of the problem is that many OSF registrations don't have valid dates for some reason, so they are filtered out on search.

**Comment by erinspace** [comment]
ran back to 2013-01-01, gathered 658 registrations that are probably those without "Test" or "Test Project" as their titles
