### ISSUE TITLE
New Harvester - Iowa State University

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#285]
OAI base url - http://lib.dr.iastate.edu/do/oai/

Make with autooai - https://github.com/erinspace/autooai

**Comment by jeffreyliu3230** [comment]
I'm taking it.

**Comment by erinspace** [comment]
Actually @jeffreyliu3230 hold off on this one for now - just got an email today that this was a test registration and they're not yet ready!

**Comment by erinspace** [comment]
Closing for now - will reopen once Iowa State registers again.
