### ISSUE TITLE
Incorrect links in TDAR Harvester

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#290]
## Summary
Some links harvested from TDAR in the SHARE OSF home page go to broken links - 

For example, [this search](https://osf.io/share/?q=Evaluation+of+Early+Human+Activities+and+Remains+in+the+Califorina+Desert&optional=source%3Atdar&sort=Relevance)

--- 

Here's the note from Adam at TDAR, who originally caught this bug:

Hi,
We've been playing with the share beta and noticed a bunch of broken
links related to content you've harvested from our site "The Digital
Archaeological Record." An example is if you search for: "Evaluation of
Early Human Activity in the California Desert" (
https://osf.io/share/?q=Evaluation+of+Early+Human+Activities+and+Remains+in+the+Califorina+Desert&optional=source%3Atdar&sort=Relevance
). The record with that title has a link to "https://osf.io/share/null".
There are many records like this, so I don't know if there was an issue
with the OAI-PMH harvest or something else, but can this be fixed?

thanks,

adam

**Comment by fabianvf** [comment]
I think I figured this out, it was an issue with backtransforming to the old API. I have fixed the back-transform, but as soon as we move to using v2 of the API this problem will go away as well.

**Comment by erinspace** [comment]
Fixed with the latest release!
