### ISSUE TITLE
Add harvester for Political Analysis

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#324]
Political Analysis is the journal of the Society for Political Methodology

https://dataverse.harvard.edu/dataverse/pan

**Comment by fabianvf** [comment]
Do dataverses have similar API/schemas?

**Comment by erinspace** [comment]
Yes! So this should be a simple one.

**Comment by fabianvf** [comment]
Cool, since we now have a couple (3 with this?) dataverse harvesters, may be a nice time to write an abstraction layer for them.

**Comment by erinspace** [comment]
Oh... so actually this one is just one dataverse inside the harvard dataverse. I think we already have the content! 

On [harvard dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/1FYXUJ)

and, [in SHARE](https://osf.io/share/?q=%22Replication+Data+for%3A+Election+Fraud%3A+A+Latent+Class+Framework+for+Digit-Based+Tests%22&optional=match%3AshareProperties.source%3Aharvarddataverse&sort=Relevance)

**Comment by fabianvf** [comment]
oh, neat

**Comment by erinspace** [comment]
Yep! That was easy!
