### ISSUE TITLE
Linting errors when not using utf8

### ISSUE THREAD

**Issue by erinspace** [fabianvf/scrapi#58]
Results coming back from PubMed are encoded with ISO-8859-1, while the default for json encoding is utf8. Right now the linter won't lint stuff that isn't utf8 encoded. 

The problem seems to be line 13 of the linter: https://github.com/fabianvf/scrapi/blob/develop/scrapi/linter/__init__.py#L13
...where it just calls json.dumps() without regard to the encoding, and the default is utf8. 

We check for the encoding in each harvester, should this be passed as an argument into the linter somehow? Should we just have a try except for a UnicodeDecodeError that then tries to decode in ISO-8859-1 if utf8 fails? 

Suggestions welcome!

**Comment by fabianvf** [comment]
Is this still an issue?

**Comment by fabianvf** [comment]
@chrisseto @erinspace
